### PR TITLE
Match generated module visibility to originating module

### LINKED ISSUE #47: Dagger error: generated module has different visibility to abstract class
Build log:
``` kotlin
DetailsViewModelModule.java:9: error: This module is public, but it includes non-public (or effectively non-public) modules. Either reduce the visibility of this module or make app.tivi.showdetails.AssistedInject_DetailsViewModelModule public.
public abstract class DetailsViewModelModule {
                ^
```

The module is just a plain Kotlin public class:
``` kotlin
@AssistedModule
@Module(includes = [AssistedInject_DetailsViewModelModule::class])
abstract class DetailsViewModelModule
```

The generated class is pkg-private so I can't see a way to make it work in Kotlin

### PR DESCRIPTION
**Pull request by JakeWharton**
Closes #47

### CODE REVIEW

File: assisted-inject-processor-dagger2/src/main/java/com/squareup/inject/assisted/dagger2/processor/AssistedInjectionModule.kt [hunk 1]
```diff
@@ -8,12 +8,14 @@ import com.squareup.javapoet.TypeName
...
 import javax.lang.model.element.Modifier.ABSTRACT
 import javax.lang.model.element.Modifier.PRIVATE
+import javax.lang.model.element.Modifier.PUBLIC
 
 private val MODULE = ClassName.get("dagger", "Module")
 private val BINDS = ClassName.get("dagger", "Binds")
 
 data class AssistedInjectionModule(
   val moduleName: ClassName,
+  val public: Boolean,
```
Comment (AlecStrong) [inline assisted-inject-processor-dagger2/src/main/java/com/squareup/inject/assisted/dagger2/processor/AssistedInjectionModule.kt]: ha. githubs having a hard time with this one
