### PR TITLE
Fix #147

### LINKED ISSUE #147: Kotlin data class with single field cannot have an assistedinject factory
The following code block pops "error: @Assisted is only supported on constructor parameters"

```kotlin
data class Foo @AssistedInject (@Assisted val bar: Bar) {
    @AssistedInject.Factory
    interface Factory {
        fun create(bar: Bar): Foo
    }
}
```

Remove the data qualifier from the class and the factory is generated as expected.

### PR DESCRIPTION
**Pull request by stoyicker**
I didn't use the exact stub generated for the data as it contained a lot of clutter that didn't seem useful. I also updated the name of the test that checks for `@Assisted` being used in non-constructor methods as otherwise I thought there could be a bit of a confusing overlap between this and the new one.

### CODE REVIEW

File: assisted-inject-processor/src/main/java/com/squareup/inject/assisted/processor/AssistedInjectProcessor.kt [hunk 1]
```diff
@@ -85,9 +85,12 @@ class AssistedInjectProcessor : AbstractProcessor() {
 
     val assistedMethods = roundEnv.findElementsAnnotatedWith<Assisted>()
         .map { it.enclosingElement as ExecutableElement }
-    // Error any non-constructor usage of @Assisted.
+    // Error any non-constructor usage of @Assisted. Methods called "copy" are also excluded due to the generated
+    // for Kotlin data classes having their parameters carry the annotations from their counterparts in the primary
+    // constructor
```
Comment (JakeWharton) [inline assisted-inject-processor/src/main/java/com/squareup/inject/assisted/processor/AssistedInjectProcessor.kt:90]: nit:
```suggestion
    // constructor.
```

See https://nedbatchelder.com/blog/201401/comments_should_be_sentences.html

**Comment by stoyicker** [comment]
@JakeWharton is there a snapshot with this anywhere?

**Comment by JakeWharton** [comment]
If you add https://oss.sonatype.org/content/repositories/snapshots/ as a Maven repo you should be able to resolve the snapshot, yes.
